"""third

Revision ID: 3525bc5299a8
Revises: 866c4bdbf8b8
Create Date: 2022-10-17 11:58:28.915517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3525bc5299a8'
down_revision = '866c4bdbf8b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
