"""admin table

Revision ID: 625975cf5384
Revises: b23c53fbc31c
Create Date: 2022-11-20 11:27:36.106635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '625975cf5384'
down_revision = 'b23c53fbc31c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.drop_constraint('student_username_firstName_lastName_email_key', 'student', type_='unique')
    op.create_unique_constraint(None, 'student', ['username', 'email'])
    op.drop_constraint('teacher_username_firstName_lastName_email_key', 'teacher', type_='unique')
    op.create_unique_constraint(None, 'teacher', ['username', 'email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher', type_='unique')
    op.create_unique_constraint('teacher_username_firstName_lastName_email_key', 'teacher', ['username', 'firstName', 'lastName', 'email'])
    op.drop_constraint(None, 'student', type_='unique')
    op.create_unique_constraint('student_username_firstName_lastName_email_key', 'student', ['username', 'firstName', 'lastName', 'email'])
    op.drop_table('admin')
    # ### end Alembic commands ###
