"""second commit

Revision ID: 866c4bdbf8b8
Revises: b24df35b3674
Create Date: 2022-10-17 11:51:59.590452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866c4bdbf8b8'
down_revision = 'b24df35b3674'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('teacher', sa.Column('email', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'email')
    op.drop_column('teacher', 'username')
    # ### end Alembic commands ###
