"""phone changes

Revision ID: 9f27ea533316
Revises: bc4153fd8046
Create Date: 2022-11-07 12:54:31.041280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f27ea533316'
down_revision = 'bc4153fd8046'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('phone', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'phone')
    # ### end Alembic commands ###
