"""varchar changes

Revision ID: e21f2a7360bc
Revises: 3525bc5299a8
Create Date: 2022-10-17 12:02:40.853270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e21f2a7360bc'
down_revision = '3525bc5299a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
